version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: walletwise-postgres
    environment:
      POSTGRES_DB: walletwise
      POSTGRES_USER: walletwise
      POSTGRES_PASSWORD: walletwise
    ports:
      - "5432:5432"
    volumes:
      - walletwise_pgdata:/var/lib/postgresql/data
    networks:
      - walletwise-net

volumes:
  walletwise_pgdata:

networks:
  walletwise-net:
    driver: bridge

